// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NHNN_OP_Hub.Data;

#nullable disable

namespace NHNN_OP_Hub.Migrations.PatientPackageDb
{
    [DbContext(typeof(PatientPackageDbContext))]
    partial class PatientPackageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NHNN_OP_Hub.Models.PatientPackage", b =>
                {
                    b.Property<int>("WorkRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkRequestID"));

                    b.Property<DateTime>("DateDispensed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaying")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("ReciptNumber")
                        .HasColumnType("int");

                    b.Property<float?>("RxCost")
                        .HasColumnType("real");

                    b.HasKey("WorkRequestID");

                    b.ToTable("PatientPackages");

                    b.HasDiscriminator<string>("PackageType").HasValue("PatientPackage");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NHNN_OP_Hub.Models.OutpatientPackage", b =>
                {
                    b.HasBaseType("NHNN_OP_Hub.Models.PatientPackage");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasCollected")
                        .HasColumnType("bit");

                    b.Property<int?>("TicketNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Outpatient");
                });

            modelBuilder.Entity("NHNN_OP_Hub.Models.PostingPackage", b =>
                {
                    b.HasBaseType("NHNN_OP_Hub.Models.PatientPackage");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasReturned")
                        .HasColumnType("bit");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Posting");
                });
#pragma warning restore 612, 618
        }
    }
}
